### ISSUE TITLE
Error when using copy of default google_checks.xml

### ISSUE THREAD

**Issue by akesser** [jdneo/vscode-checkstyle#280]
Hello there,
when I copy the content of the default google_checks.xml (https://github.com/checkstyle/checkstyle/blob/master/src/main/resources/google_checks.xml)  file to a custom checkstyle.xml to change some settings (e.g. the max value of LineLength) and try to set this file as the configuration file, I get the following error: 
Module TreeWalker initialization failed. It my be caused by wrong configuration or incompatible version.

Im using version 8.33 of checkstyle and version 1.3.3 of Checkstyle for java

Thanks for your help in advance

**Comment by Shinigami92** [comment]
Is there a way to get the builtin `google_checks.xml` file, so I can copy this one instead of the one from `master`?
Maybe they are different? 🤷‍♂️

`vscode-checkstyle` logs something like this to output:

```
{"message":"cannot initialize module TreeWalker - Token \"ENUM_DEF\" was not found in Acceptable tokens list in check com.puppycrawl.tools.checkstyle.checks.blocks.RightCurlyCheck"}

// Removing RightCurly.tokens

{"message":"cannot initialize module TreeWalker - Token \"LABELED_STAT\" was not found in Acceptable tokens list in check com.puppycrawl.tools.checkstyle.checks.whitespace.NoWhitespaceBeforeCheck"}

// Removing NoWhitespaceBefore.tokens
// Now it's working 🤔 
```

**Comment by akesser** [comment]
Thanks for the hint.

With java.checkstyle.version 8.33 it is enough to remove `INTERFACE_DEF` from `RightCurly.Tokens`get get it working.

**Comment by jdneo** [comment]
Unfortunately, Checkstyle's rules set is not backward compatible. So when you update your rules or the version of Checkstyle, there might be some possibility to encounter such a problem. So please do make sure your rules are compatible with the active Checkstyle version.

> Is there a way to get the builtin google_checks.xml file?

@Shinigami92, instead of directly copying from the master branch, you should get the files from the related version tag, for example, the tag for 8.33: https://github.com/checkstyle/checkstyle/tree/checkstyle-8.33 

I'm closing this issue since it seems not a extension's bug.
